/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teamproject;

import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;

/**
 *
 * @author Ramee
 */
public class Bapers extends javax.swing.JFrame {

    /**
     * Creates new form Bapers
     */
    private CardLayout card;
    private CardLayout customerCard;
    
    public Bapers() {
        initComponents();
        this.setTitle("Bapers System");
        
         CardLayout card = (CardLayout)mainPanel.getLayout();
         this.card = card;
         
         CardLayout card1 = (CardLayout)customerCard1.getLayout();
         this.customerCard = card1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filterCustomerList = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        homepage = new javax.swing.JPanel();
        customerPanel = new javax.swing.JPanel();
        customerLabel = new javax.swing.JLabel();
        Customersbtn = new javax.swing.JButton();
        customerInfoBtn = new javax.swing.JButton();
        addCustomerBtn = new javax.swing.JButton();
        jobsPanel = new javax.swing.JPanel();
        jobsLabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        reportsPanel = new javax.swing.JPanel();
        reportsLabel = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        paymentPanel = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        TasksPanel = new javax.swing.JPanel();
        taskLabel = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        adminLabel = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        viewJob = new javax.swing.JPanel();
        reports = new javax.swing.JPanel();
        payment = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Tasks = new javax.swing.JPanel();
        admin = new javax.swing.JPanel();
        customers = new javax.swing.JPanel();
        customerCard1 = new javax.swing.JPanel();
        customerMain = new javax.swing.JPanel();
        customerMainPage = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        CustomerPageTitle = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        valuedRadioButton = new javax.swing.JRadioButton();
        normalRadioButton = new javax.swing.JRadioButton();
        inDefaultRadioButton = new javax.swing.JRadioButton();
        allRadioButton = new javax.swing.JRadioButton();
        filterRadioBoxLabel = new javax.swing.JLabel();
        upgradeDowngradeBtn = new javax.swing.JButton();
        createJobBtn = new javax.swing.JButton();
        createNewAccountBtn = new javax.swing.JButton();
        generateInDefaultBtn = new javax.swing.JButton();
        downgradeBtn = new javax.swing.JButton();
        addNewCustomerAccount = new javax.swing.JPanel();
        forenameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        accountIDLabel = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        createAccountBtn = new javax.swing.JButton();
        foreNameTextField = new javax.swing.JTextField();
        surNameTextField = new javax.swing.JTextField();
        dateOfBirthTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        phoneNumberTextfield = new javax.swing.JTextField();
        accountIDTextField = new javax.swing.JTextField();
        viewCustomer = new javax.swing.JPanel();
        homepageBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        viewJobsbtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        PaymentBtn = new javax.swing.JButton();
        taskBtn = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        loggedinLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(204, 204, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        homepage.setBackground(new java.awt.Color(153, 153, 153));

        customerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerLabel.setText("Customers");

        Customersbtn.setText("Customers");

        customerInfoBtn.setText("Customer Info");
        customerInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerInfoBtnActionPerformed(evt);
            }
        });

        addCustomerBtn.setText("Add Customer");

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Customersbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(customerLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Customersbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerInfoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCustomerBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jobsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jobsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jobsLabel.setText("Jobs");

        jButton5.setText("View Jobs");

        jButton6.setText("Create Job");

        javax.swing.GroupLayout jobsPanelLayout = new javax.swing.GroupLayout(jobsPanel);
        jobsPanel.setLayout(jobsPanelLayout);
        jobsPanelLayout.setHorizontalGroup(
            jobsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobsPanelLayout.createSequentialGroup()
                .addGroup(jobsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6)
                    .addGroup(jobsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jobsPanelLayout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jobsLabel))
                        .addGroup(jobsPanelLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jButton5))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jobsPanelLayout.setVerticalGroup(
            jobsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jobsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        reportsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        reportsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reportsLabel.setText("Reports");

        jButton7.setText("Individual Report");

        jButton8.setText("Individual Performance");

        jButton9.setText("Summary Performance");

        javax.swing.GroupLayout reportsPanelLayout = new javax.swing.GroupLayout(reportsPanel);
        reportsPanel.setLayout(reportsPanelLayout);
        reportsPanelLayout.setHorizontalGroup(
            reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportsLabel)
                .addGap(70, 70, 70))
            .addGroup(reportsPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        reportsPanelLayout.setVerticalGroup(
            reportsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportsLabel)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(12, 12, 12)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        paymentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        paymentLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paymentLabel.setText("Payment");

        jButton10.setText("View Payments");

        jButton11.setText("Pay Now");

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(paymentLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paymentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        TasksPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        taskLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        taskLabel.setText("Tasks");

        jButton12.setText("View Tasks");

        javax.swing.GroupLayout TasksPanelLayout = new javax.swing.GroupLayout(TasksPanel);
        TasksPanel.setLayout(TasksPanelLayout);
        TasksPanelLayout.setHorizontalGroup(
            TasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TasksPanelLayout.createSequentialGroup()
                .addGroup(TasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TasksPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(taskLabel))
                    .addGroup(TasksPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton12)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        TasksPanelLayout.setVerticalGroup(
            TasksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TasksPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        AdminPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        adminLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adminLabel.setText("Admin");

        jButton13.setText("View Admin Tab");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminLabel)
                .addGap(73, 73, 73))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homepageLayout = new javax.swing.GroupLayout(homepage);
        homepage.setLayout(homepageLayout);
        homepageLayout.setHorizontalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepageLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jobsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TasksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        homepageLayout.setVerticalGroup(
            homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homepageLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homepageLayout.createSequentialGroup()
                        .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jobsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(homepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TasksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(homepageLayout.createSequentialGroup()
                        .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        mainPanel.add(homepage, "homepage");

        viewJob.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout viewJobLayout = new javax.swing.GroupLayout(viewJob);
        viewJob.setLayout(viewJobLayout);
        viewJobLayout.setHorizontalGroup(
            viewJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        viewJobLayout.setVerticalGroup(
            viewJobLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(viewJob, "viewJob");

        reports.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout reportsLayout = new javax.swing.GroupLayout(reports);
        reports.setLayout(reportsLayout);
        reportsLayout.setHorizontalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        reportsLayout.setVerticalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(reports, "reports");

        payment.setBackground(new java.awt.Color(255, 0, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout paymentLayout = new javax.swing.GroupLayout(payment);
        payment.setLayout(paymentLayout);
        paymentLayout.setHorizontalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        paymentLayout.setVerticalGroup(
            paymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainPanel.add(payment, "payment");

        Tasks.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout TasksLayout = new javax.swing.GroupLayout(Tasks);
        Tasks.setLayout(TasksLayout);
        TasksLayout.setHorizontalGroup(
            TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        TasksLayout.setVerticalGroup(
            TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(Tasks, "Tasks");

        admin.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        mainPanel.add(admin, "card4");

        customers.setBackground(new java.awt.Color(204, 204, 204));
        customers.setLayout(new java.awt.CardLayout());

        customerCard1.setLayout(new java.awt.CardLayout());

        customerTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        customerTable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "customerID", "customerName", "customerStatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setCellSelectionEnabled(true);
        customerTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        customerTable.getTableHeader().setReorderingAllowed(false);
        customerMainPage.setViewportView(customerTable);

        CustomerPageTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CustomerPageTitle.setText("CustomerList");

        jTextField1.setText("search ID");

        filterCustomerList.add(valuedRadioButton);
        valuedRadioButton.setText("Valued");

        filterCustomerList.add(normalRadioButton);
        normalRadioButton.setText("Normal");

        filterCustomerList.add(inDefaultRadioButton);
        inDefaultRadioButton.setText("In-Default");

        filterCustomerList.add(allRadioButton);
        allRadioButton.setSelected(true);
        allRadioButton.setText("All");
        allRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRadioButtonActionPerformed(evt);
            }
        });

        filterRadioBoxLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        filterRadioBoxLabel.setText("Filter");

        upgradeDowngradeBtn.setText("Upgrade");

        createJobBtn.setText("Create Job");

        createNewAccountBtn.setText("Create New Account");

        generateInDefaultBtn.setText("Generate In-Default");

        downgradeBtn.setText("Downgrade");

        javax.swing.GroupLayout customerMainLayout = new javax.swing.GroupLayout(customerMain);
        customerMain.setLayout(customerMainLayout);
        customerMainLayout.setHorizontalGroup(
            customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerMainLayout.createSequentialGroup()
                .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerMainLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(CustomerPageTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerMainLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(customerMainLayout.createSequentialGroup()
                                .addComponent(customerMainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(customerMainLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(filterRadioBoxLabel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(customerMainLayout.createSequentialGroup()
                                        .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(valuedRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(normalRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(inDefaultRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(allRadioButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                        .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(generateInDefaultBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(createNewAccountBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                            .addComponent(createJobBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(upgradeDowngradeBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(downgradeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addGap(32, 32, 32))
        );
        customerMainLayout.setVerticalGroup(
            customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CustomerPageTitle)
                .addGap(12, 12, 12)
                .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerMainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(customerMainLayout.createSequentialGroup()
                        .addComponent(filterRadioBoxLabel)
                        .addGap(16, 16, 16)
                        .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upgradeDowngradeBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(valuedRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(downgradeBtn)
                            .addComponent(normalRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inDefaultRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createJobBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(allRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createNewAccountBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generateInDefaultBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        customerCard1.add(customerMain, "customerMain");
        customerMain.getAccessibleContext().setAccessibleName("");
        customerMain.getAccessibleContext().setAccessibleDescription("");

        forenameLabel.setText("Forename");

        surnameLabel.setText("Surname");

        dateLabel.setText("Date of Birth");

        addressLabel.setText("Address");

        phoneNumberLabel.setText("Phone Number");

        accountIDLabel.setText("AccountID");

        cancelBtn.setText("Cancel");

        createAccountBtn.setText("create Account");

        javax.swing.GroupLayout addNewCustomerAccountLayout = new javax.swing.GroupLayout(addNewCustomerAccount);
        addNewCustomerAccount.setLayout(addNewCustomerAccountLayout);
        addNewCustomerAccountLayout.setHorizontalGroup(
            addNewCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewCustomerAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewCustomerAccountLayout.createSequentialGroup()
                        .addComponent(createAccountBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 559, Short.MAX_VALUE)
                        .addComponent(cancelBtn)
                        .addGap(43, 43, 43))
                    .addGroup(addNewCustomerAccountLayout.createSequentialGroup()
                        .addGroup(addNewCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(accountIDTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(phoneNumberTextfield)
                            .addComponent(AddressTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(forenameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surnameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneNumberLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountIDLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foreNameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addNewCustomerAccountLayout.setVerticalGroup(
            addNewCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewCustomerAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(forenameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foreNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateOfBirthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(phoneNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(accountIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(addNewCustomerAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(createAccountBtn))
                .addGap(21, 21, 21))
        );

        customerCard1.add(addNewCustomerAccount, "addnewcustomerCard");
        addNewCustomerAccount.getAccessibleContext().setAccessibleName("addnewcustomer");

        javax.swing.GroupLayout viewCustomerLayout = new javax.swing.GroupLayout(viewCustomer);
        viewCustomer.setLayout(viewCustomerLayout);
        viewCustomerLayout.setHorizontalGroup(
            viewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        viewCustomerLayout.setVerticalGroup(
            viewCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        customerCard1.add(viewCustomer, "customerinfo");

        customers.add(customerCard1, "card5");

        mainPanel.add(customers, "customers");

        homepageBtn.setText("homepage");
        homepageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageBtnActionPerformed(evt);
            }
        });

        customerBtn.setText("customers");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        viewJobsbtn.setText("viewJob");

        reportsBtn.setText("reports");

        PaymentBtn.setText("payment");

        taskBtn.setText("Tasks");

        logoLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        logoLabel.setText("LOGO");

        logoutBtn.setText("Logout");

        loggedinLabel.setText("Logged In As:");

        userLabel.setText("N/a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loggedinLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(homepageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewJobsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(reportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(PaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(taskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(loggedinLabel)
                        .addComponent(userLabel))
                    .addComponent(logoutBtn)
                    .addComponent(logoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homepageBtn)
                    .addComponent(customerBtn)
                    .addComponent(viewJobsbtn)
                    .addComponent(reportsBtn)
                    .addComponent(PaymentBtn)
                    .addComponent(taskBtn))
                .addGap(51, 51, 51)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerBtnActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void customerInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerInfoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerInfoBtnActionPerformed

    private void homepageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homepageBtnActionPerformed

    private void allRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JLabel CustomerPageTitle;
    private javax.swing.JButton Customersbtn;
    private javax.swing.JButton PaymentBtn;
    private javax.swing.JPanel Tasks;
    private javax.swing.JPanel TasksPanel;
    private javax.swing.JLabel accountIDLabel;
    private javax.swing.JTextField accountIDTextField;
    private javax.swing.JButton addCustomerBtn;
    private javax.swing.JPanel addNewCustomerAccount;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel admin;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JRadioButton allRadioButton;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JButton createJobBtn;
    private javax.swing.JButton createNewAccountBtn;
    private javax.swing.JButton customerBtn;
    private javax.swing.JPanel customerCard1;
    private javax.swing.JButton customerInfoBtn;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JPanel customerMain;
    private javax.swing.JScrollPane customerMainPage;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JPanel customers;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateOfBirthTextField;
    private javax.swing.JButton downgradeBtn;
    private javax.swing.ButtonGroup filterCustomerList;
    private javax.swing.JLabel filterRadioBoxLabel;
    private javax.swing.JTextField foreNameTextField;
    private javax.swing.JLabel forenameLabel;
    private javax.swing.JButton generateInDefaultBtn;
    private javax.swing.JPanel homepage;
    private javax.swing.JButton homepageBtn;
    private javax.swing.JRadioButton inDefaultRadioButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jobsLabel;
    private javax.swing.JPanel jobsPanel;
    private javax.swing.JLabel loggedinLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton normalRadioButton;
    private javax.swing.JPanel payment;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextfield;
    private javax.swing.JPanel reports;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JLabel reportsLabel;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JTextField surNameTextField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JButton taskBtn;
    private javax.swing.JLabel taskLabel;
    private javax.swing.JButton upgradeDowngradeBtn;
    private javax.swing.JLabel userLabel;
    private javax.swing.JRadioButton valuedRadioButton;
    private javax.swing.JPanel viewCustomer;
    private javax.swing.JPanel viewJob;
    private javax.swing.JButton viewJobsbtn;
    // End of variables declaration//GEN-END:variables

    void navigationBar(Controller.BapersMenu bapersNavi) {
        homepageBtn.addActionListener(bapersNavi);
        customerBtn.addActionListener(bapersNavi);
        PaymentBtn.addActionListener(bapersNavi);
        viewJobsbtn.addActionListener(bapersNavi);
        taskBtn.addActionListener(bapersNavi);
        reportsBtn.addActionListener(bapersNavi);
        logoutBtn.addActionListener(bapersNavi);
    }
    
    
    
    
    
    public void setpanel(String x){
        card.show(mainPanel, x);

    }
    
    public void setPanelCustomer(String x){
        card.show(mainPanel,"customers");
        customerCard.show(customerCard1, x);
        
        
        
    
    }
    
     public void setPanelTest(){
         card.show(mainPanel,"customers");
         customerCard.show(customerCard1,"addnewcustomerCard" );
         System.out.println("test ");
    
    }
    
    public void setUser(String x){
    
    userLabel.setText(x);
    }
    
    public JPanel getMainPanel(){
    
    return mainPanel;
     
    }
    
    public JTable getCustomerTable(){
        
    return customerTable;
    }

    void CustomerPanelNavigation(Controller.CustomerPanelNavigation CustomerNavigation) {
    Customersbtn.addActionListener(CustomerNavigation);
    addCustomerBtn.addActionListener(CustomerNavigation);
    customerInfoBtn.addActionListener(CustomerNavigation);
    }
    
    public ButtonGroup filterSelection(){
    
          
    
            return filterCustomerList;
    }

    void CustomerMain(Controller.CustomerMain customerMain) {
        
        valuedRadioButton.addActionListener(customerMain);
        normalRadioButton.addActionListener(customerMain);
        inDefaultRadioButton.addActionListener(customerMain);
        allRadioButton.addActionListener(customerMain);
        
        upgradeDowngradeBtn.addActionListener(customerMain);
        downgradeBtn.addActionListener(customerMain);
        createJobBtn.addActionListener(customerMain);
        createNewAccountBtn.addActionListener(customerMain);
        generateInDefaultBtn.addActionListener(customerMain);
        
    }
    
    public JRadioButton getValuedRadioButton(){
    
     return valuedRadioButton;
    }
    
    public JRadioButton getNormalRadioButton(){
    
     return normalRadioButton;
    }
    
    public JRadioButton getInDefaultRadioButton(){
    
     return inDefaultRadioButton;
    }
    
    public JRadioButton getAllRadioButton(){
    
     return allRadioButton;
    }
    
    public String getCustomerName(){
    
    String name = foreNameTextField.getText() + surNameTextField.getText();
    
    return name;
    }

    void createCustomer(Controller.CreateNewCustomer createNewCustomer) {
       createAccountBtn.addActionListener(createNewCustomer);
    }
    
  
}
